### ISSUE TITLE
In pages/But.md sono presenti tre paragrafi in italiano

### ISSUE THREAD

**Issue by Rubo3** [xplosionmind/quitsocialmedia.club#16]
In [questo](https://github.com/xplosionmind/quitsocialmedia.club/commit/8f28984799a3fa04d3d305c734e5a05fcedcc5b9#diff-2929cd34ea84f2bb47cc164ab97d7a34ecb3abab17b90071606abfb20d9cfcd5) _commit_ `pages/But.md` è stato tradotto in inglese, ma tre paragrafi sono rimasti in italiano.

**Comment by xplosionmind** [comment]
Giusto, è intenzionale: come tutte le traduzioni abbandonate a metà, la parte incompleta, invece di essere assente, è presente nella lingua originale. Quando verrà tradotta la parte mancante, sarà sostituito.

---

It is intentional that pages containing an incomplete localization still contain the untranslated section in the original language. It is being substituted one the translation will be written.
